### ISSUE TITLE
[Communication to the public] Correct the article in the ZDF (german tv)

### ISSUE THREAD

**Issue by jucktnich** [eu-digital-green-certificates/dgc-overview#11]
## Your Issue

There's an article in the ZDF (https://www.zdf.de/nachrichten/politik/corona-digitale-impfausweise-100.html german) which talks about "massive security flaws" in the digital green pass. I think all the flaws criticised there, except the possibility of getting hacked, are also in the paper pass. I thought there should be a clarification, cause this implicates, that the digital certificate is so much worse than the paper pass. (Sorry didn't found a better way to contact an official.)

**Comment by daniel-eder** [comment]
@jucktnich thank you! The European Commission and German Officials are aware of this situation and there are ongoing discussions on how to address the root cause of the mentioned security issues in Germany, namely the transfer from paper pass to digital pass without strict verification procedures.
