### ISSUE TITLE
Update Fork of dgc-schema to version 1.0.0.

### ISSUE THREAD

**Issue by SZoerner** [eu-digital-green-certificates/dgc-overview#25]
## Your Issue

This organisation contains a Fork of the JSON Schema repository from the eHealth network, pointing to an [outdated draft version of the schema](https://github.com/eu-digital-green-certificates/ehn-dgc-schema).

This fork should be updated to the [version 1.0.0](https://github.com/ehn-digital-green-development/ehn-dgc-schema/releases/tag/1.0.0), so that member states have a common view on the current implementation baseline.

**Comment by daniel-eder** [comment]
Schema has been updated meanwhile
