### ISSUE TITLE
Best way to report security issues?

### ISSUE THREAD

**Issue by oc-ja** [eu-digital-green-certificates/dgc-overview#29]
Hello everyone,

if I have found a security risk, which I think would be best addressed at the specification/requirements-level, whom should I contact and how?

I should note, that I'm not part of any development team currently implementing the specification, so I don't have any internal contacts.

Thank you!

Regards,

Jan

**Comment by daniel-eder** [comment]
@oc-ja Thank you for your report! May I ask you to mail daniel.eder@magenta.at? I'll forward internally and my colleagues will be in touch if they need more information.

**Comment by daniel-eder** [comment]
Thank you for your report - we'll continue this via mail!
