### ISSUE TITLE
Certificate validation for airlines and non-EU countries

### ISSUE THREAD

**Issue by han-morten** [eu-digital-green-certificates/dgc-overview#33]
## Certificate validation for airlines and non-EU countries

My company represents some non-EU countries that need to be able to validate digital health certificates from many countries, including EU countries. I am happy to see that your code is available on GitHub, but I don't see how the architecture allows for non-EU countries or other 3rd parties to validate EU certificates. Can someone please share some information on this?

From what I understand, we would need access to the trust list. Can this be obtained without a trusted gateway node, outside of the "circle of trust" ? Such countries have no requirement to issue certificates, just to validate them, so need to be able to read the trust list, without being able to upload certificates.

Hope to hear back!

Morten Jorgensen
Travizory Border Security

**Comment by daniel-eder** [comment]
Hi @han-morten generally speaking in this phase the project as it is developed in this GitHub organization is targeted at EU Member States, non-EU countries should get in touch with the European Commission / eHealth Network to coordinate further steps. If you do not have a point of contact, please get in touch with me at daniel.eder@magenta.at and I'll point you in the right direction

**Comment by daniel-eder** [comment]
Sent e-mail to get in touch with EU eHealth Network.

**Comment by alexandermainz** [comment]
Hello,
I would be interested in an answer to that question, too.
We would like to integrate the validation into our gastro software so that our staff does not need to use their private smartphones with the CovPassCheck app.
Is there a publicly available URI where one can obtain the public key to a given `kid` from a given issuer or something like a JWKS?
Kind regards,
Alex
