### ISSUE TITLE
How to access the primary (global) trust list

### ISSUE THREAD

**Issue by jnischler** [eu-digital-green-certificates/dgc-overview#34]
Hey everyone,

first of all thanks for this awesome work in such a short time.

To verify all the different codes we need access to a global trust list.
Of course only to access the public keys.

We found one list for Austria, but this list looks more like a test list.
But using this list we are able to verify code for Austria but cant verify other countries.

Maybe I did get something wrong or why is the trust list not public accessible.
The public keys are no sensitive information.

https://dgc.a-sit.at/ehn/cert/listv2
https://dgc.a-sit.at/ehn/cert/sigv2
https://dgc.a-sit.at/ehn/

relevant issues:
https://github.com/ehn-dcc-development/hcert-kotlin/issues/28
https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10

thanks and best regards
Julian

**Comment by jnischler** [comment]
Looking at this document:
https://github.com/eu-digital-green-certificates/dgc-overview/blob/main/guides/certificate-governance.md

It seams like the trust list provided by the EU is only exchanged with the national backends, so no public access there ?
Is this intentional ?

So we would need to get access and connect to the national backend of a country?
Our development is located in Austria but we are operating services all over Europe.

thanks

**Comment by daniel-eder** [comment]
Closing this, see #10
