### ISSUE TITLE
Is it possible for service providers to use the gateway directly somehow?

### ISSUE THREAD

**Issue by piotrblasiak** [eu-digital-green-certificates/dgc-overview#40]
I am trying to figure out if there is a way for third party apps & services to validate the QR codes?

**Comment by daniel-eder** [comment]
To validate the QR codes third party apps and services need access to the list of public keys ( trust list ). Each member state has their own trust list and can decide how to grant access. See https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10 for a discussion on the topic.
