### ISSUE TITLE
DGC Server Urls for Public keys (Public APIs)

### ISSUE THREAD

**Issue by bencevegert** [eu-digital-green-certificates/dgc-overview#41]
Hello!

Where we can find a list of the production Urls of the different national DGC Servers (public key Apis) for testing purpose?
We are developing a Windows C# WPF green pass checker application, and we just found the Sweden Url (https://dgcg.covidbevis.se/tp/trust-list)?

Thanks a lot.

**Comment by daniel-eder** [comment]
There is no central list of the URLs - the member states have sovereignty over their endpoints for the public keys and may choose to publish them.

See also https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10
