### ISSUE TITLE
public keys to check COSE signatures

### ISSUE THREAD

**Issue by simonh1000** [eu-digital-green-certificates/dgc-overview#43]
I'm trying to decode the certificates in Elm (compiles to JavaScript in the browser). I can read the data fine, but don't know where to look for

- instructions to check the signing of the data, although I can probably work that out;
- the public keys themselves. 

any pointers?

**Comment by daniel-eder** [comment]
Hi @simonh1000 
Regarding your questions:
- For working with the certificates please refer to the [spec](https://github.com/ehn-dcc-development/hcert-spec) and to our sample implementations, e.g. https://github.com/eu-digital-green-certificates/dgca-verifier-service and https://github.com/eu-digital-green-certificates/dgca-verifier-app-android 
- For the public keys you need to contact your national health authority, see also https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10 for a discussion on the topic
