### ISSUE TITLE
test dgca-issuance

### ISSUE THREAD

**Issue by hachembhl** [eu-digital-green-certificates/dgc-overview#47]
Hi,
I would like to test dgca-issuance-service component, after build and run, i got error message bellow
![issuance error message](https://user-images.githubusercontent.com/89782607/131499602-6da0c6bd-4492-4c25-b3e3-5a826116cb20.PNG)

what i can do to perform test?

**Comment by daniel-eder** [comment]
I opened an issue in the relevant repository: https://github.com/eu-digital-green-certificates/dgca-issuance-service/issues/89
