### ISSUE TITLE
Issues with evolution off the published JSON schema version

### ISSUE THREAD

**Issue by pjsramos** [eu-digital-green-certificates/dgc-overview#5]
https://ec.europa.eu/health/sites/health/files/ehealth/docs/digital-green-certificates_dt-specifications_en.pdf

I think the published scheme has some problems:
1. The lack of a "version" field to accommodate future changes to this schema. If more than one version of the DGC is in circulation, validation applications cannot distinguish between them without a version field. This field is present in more recent versions: https://github.com/ehn-digital-green-development/ehn-dgc-schema/blob/main/DGC.schema.json
2. The datasets for disease-agent-targeted,  vaccine-prophylaxis, vaccine-medicinal-product, test-manf, etc are hard-coded in the schema and don't accommodate for the future update of this values to add new vaccines or tests. I think this datasets must be maintained outside of the schema.

**Comment by SchulzeStTSI** [comment]
@dirkx How is the current state in schema discussions here?

**Comment by SZoerner** [comment]
By now, the current [version 1.0.0](https://github.com/ehn-digital-green-development/ehn-dgc-schema/releases/tag/1.0.0) does [include a version field](https://github.com/ehn-digital-green-development/ehn-dgc-schema/blob/58605fffbe48a7cf77f55d2ce535cd1c4b167cd3/DGC.schema.json#L15) as well as [separating the value sets](https://github.com/ehn-digital-green-development/ehn-dgc-schema/pull/30) from the core schema. 
@pjsramos do you think this issue can be closed then?

**Comment by pjsramos** [comment]
@SZoerner this is good news. I think with this changes we can close this issue.
