### ISSUE TITLE
Running a custom verification service

### ISSUE THREAD

**Issue by ikarstein** [eu-digital-green-certificates/dgc-overview#56]
I have been asked by one of my customers to write a custom DCC verification service. Here are TONS of information, but the "verification guide" is empty (https://github.com/eu-digital-green-certificates/dgc-overview/blob/main/guides/validation-guide.md).

It's also not clear how to obtain access to the test gateway (and later acceptance and production). I created an issue here: https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/13#issue-1071444390

For any information I would be very grateful!

**Comment by daniel-eder** [comment]
Applications do not directly interact with the gateway, but rather with national backends (which in turn communicate with the gateway), so the access to the gateway is limited to countries in the onboarding process.

Private organizations can participate in the system by accessing their respective national backend to obtain public keys. Generally speaking the point of contact is then the health authority in the country the system is supposed to run, but there are also some countries that offer public access. You can find a discussion on the topic here: https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10
