### ISSUE TITLE
How to validate/decode a QR code with recovery or vaccination?

### ISSUE THREAD

**Issue by vinaybedre** [eu-digital-green-certificates/dgc-overview#59]
## How to use DGC's service to validate/decode a QR code containing recovery or vaccination?

I came across https://www.npmjs.com/package/covid-certificate-parser with which we will be able to decode/parse a QR code with recovery/vaccination information offline.

What I am unable to understand is, how can I make use of DGC API/Service to validate/decode a QR code and check the authenticity of the QR code. 

Is it possible? Does DGC provide some public APIs where a private company can connect to validate the authenticity of the QR code?

**Comment by daniel-eder** [comment]
The DCC Gateway is not available directly to third parties, it only interacts with national backends. It's the national backends that provide the public keys needed for verification to the applications.

See https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10 for a discussion on how to access the national backends
